Apply automatic identity selection for forwarding emails based on `to:` field of mail being forwarded
k9mail/k-9 pull request #5009
Opened 2020-10-14 17:48 UTC by anadi198

fixes #4791 

> ### My proposal:
> Include `Action.FORWARD` and `Action.FORWARD_AS_ATTACHMENT` to the if-condition here:
> 
> https://github.com/k9mail/k-9/blob/b9eba6971fa86b95a4855caddbfa7144e5c23884/app/ui/legacy/src/main/java/com/fsck/k9/activity/MessageCompose.java#L1281-L1287

The line number referenced above are inside `processMessageToReplyTo(...)` and so adding logic for forwarded message didn't work(I checked using debugger to make sure). Luckily, right below that block of code is the method `processMessageToForward` - inside which I added the logic highlighted by @simontb. 
 
I had to do some research to understand the use of identity which I think is quite useful! Anyway, after following #935 discussion I think I've understood the goal somewhat. For reply to an email, the to: email is used to check for existing identities and if found, the found identity is used instead of default one to fill inside the from field of the new message. Please correct me if I got something wrong.

What I've achieved is an effect exactly like the reply feature, when I forward a mail sent to id+1@domain.com, the default identity(id@domain.com) is not filled inside from :, instead the identity associated with id+1@domain.com is used.

2020-10-14 17:59 UTC, anadi198 commented
I used the settings.jar for code style guidelines and I think I once pressed the code reformat shortcut which caused some extra changes in the file(at 3-5 places) by Android Studio, please tell me if I have to do anything about them.

> Updated (2020/10/05 15:00 UTC): Individual pull requests can also be directly opted-in to Hacktoberfest with the ‘hacktoberfest-accepted’ label, on any public GitHub repository, without the need for the ‘hacktoberfest’ repository topic.

If its not too much to ask, could you please add this label to my PR if it's acceptable? It could help me win some [swag](https://hacktoberfest.digitalocean.com/hacktoberfest-update) :)

2020-10-15 15:49 UTC, cketti requested changes
This seems to work fine :+1:

The change needs some cleaning up, though. Please undo all the changes to lines you haven't touched. You can use the "Reformat file…" action and then select "Only VCS changed text" to only reformat the code you've added/changed.

I've also added a comment on how to refactor the code to make it a bit cleaner.

2020-10-15 16:53 UTC, cketti approved these changes

2020-10-15 17:04 UTC, merged

2020-10-15 17:05 UTC, cketti commented
Thanks :+1: