Inline attachments are included in forwarded messages
k9mail/k-9 pull request #5330
Opened 2021-06-08 06:32 UTC by plan3d

Resolves #2490

I can reproduce the issue by forwarding the following mail:

```
To: x@example.com
From: y@example.com
Subject: inline attachment
Message-ID: <XXX>
Date: XXX
User-Agent: XXX
MIME-Version: 1.0
Content-Type: multipart/alternative;
 boundary="------------6DA55383243B64A886F2E3C6"
Content-Language: en-US

This is a multi-part message in MIME format.
--------------6DA55383243B64A886F2E3C6
Content-Type: text/plain; charset=utf-8; format=flowed
Content-Transfer-Encoding: 7bit

text with image 1x1 test

--------------6DA55383243B64A886F2E3C6
Content-Type: multipart/related;
 boundary="------------84EA168083F5E842FCF139D3"

--------------84EA168083F5E842FCF139D3
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: 7bit

<html>
  <head>

    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  </head>
  <body>
    <p>text with image <img moz-do-not-send="false"
        src="cid:part1.09AEA62C.20716EEE" alt="1x1" width="1"
        height="1"> test<br>
    </p>
  </body>
</html>

--------------84EA168083F5E842FCF139D3
Content-Type: image/png;
 name="1x1.png"
Content-Transfer-Encoding: base64
Content-ID: <part1.09AEA62C.20716EEE>
Content-Disposition: inline;
 filename="1x1.png"

iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAADElEQVQI12P4//8/AAX+Av7c
zFnnAAAAAElFTkSuQmCC
--------------84EA168083F5E842FCF139D3--

--------------6DA55383243B64A886F2E3C6--

```

2021-06-10 07:27 UTC, cketti commented
Thanks for the pull request :+1:

I currently don't have the bandwidth to review your changes. I'm hoping I'll get to it next week.

2021-06-11 05:32 UTC, plan3d commented
:+1:, no problem :-)

2021-06-29 21:20 UTC, cketti requested changes
I've forgotten how awful loaders are :cry: 
Kudos for digging through this code and coming up with a fix :+1: 

I like the approach. The PR needs some minor adjustments and could use some cosmetic changes. Otherwise it's great :ok_hand:

2021-06-29 21:20 UTC, cketti commented on app/ui/legacy/src/test/java/com/fsck/k9/activity/compose/AttachmentPresenterTest.kt
> +class AttachmentPresenterTest : K9RobolectricTest() {
Nice :+1:

2021-07-06 19:02 UTC, plan3d commented on app/ui/legacy/src/main/java/com/fsck/k9/activity/compose/AttachmentPresenter.java
> +        Map<String, com.fsck.k9.message.Attachment> result = new HashMap<>();
Done

2021-07-06 19:03 UTC, plan3d commented on app/ui/legacy/src/main/java/com/fsck/k9/activity/compose/AttachmentPresenter.java
>              if (attachmentViewInfo.inlineAttachment) {
Renamed to `loadAllAvailableAttachments()`

2021-07-06 19:03 UTC, plan3d commented on app/ui/legacy/src/main/java/com/fsck/k9/activity/compose/AttachmentPresenter.java
> +                }
Done

2021-07-06 19:04 UTC, plan3d commented on app/ui/legacy/src/test/java/com/fsck/k9/activity/compose/AttachmentPresenterTest.kt
> +    private val attachmentMvpView = mock(AttachmentPresenter.AttachmentMvpView::class.java)
Done

2021-07-06 19:04 UTC, plan3d commented on app/ui/legacy/src/test/java/com/fsck/k9/activity/compose/AttachmentPresenterTest.kt
> +    private val URI = Uri.Builder().scheme("content://").build()
Done, please check if warning is gone

2021-07-06 19:05 UTC, plan3d commented on app/ui/legacy/src/test/java/com/fsck/k9/activity/compose/AttachmentPresenterTest.kt
> +    lateinit var toTest: AttachmentPresenter
Renamed to `attachmentPresenter`

2021-07-06 19:06 UTC, plan3d commented on app/ui/legacy/src/test/java/com/fsck/k9/activity/compose/AttachmentPresenterTest.kt
> +        }.whenever(loaderManager).initLoader(anyInt(), any(), any(LoaderManager.LoaderCallbacks::class.java))
Moved to new function `mockLoaderManager(attachmentSupplier: Supplier<Attachment>)`

2021-07-06 19:06 UTC, plan3d commented on app/ui/legacy/src/test/java/com/fsck/k9/activity/compose/AttachmentPresenterTest.kt
> +            )
Done

2021-07-06 19:06 UTC, plan3d commented on app/ui/legacy/src/test/java/com/fsck/k9/activity/compose/AttachmentPresenterTest.kt
> +        assertEquals(1, toTest.attachments.size)
Done

2021-07-06 19:06 UTC, plan3d commented on app/ui/legacy/src/test/java/com/fsck/k9/activity/compose/AttachmentPresenterTest.kt
> +                it.arguments[2] as LoaderManager.LoaderCallbacks<Attachment>
Done

2021-07-06 19:06 UTC, plan3d commented on app/ui/legacy/src/test/java/com/fsck/k9/activity/compose/AttachmentPresenterTest.kt
> +                mock(Loader::class.java) as Loader<Attachment>,
Done

2021-07-06 19:07 UTC, plan3d commented on app/ui/legacy/src/test/java/com/fsck/k9/activity/compose/AttachmentPresenterTest.kt
> +        }.whenever(loaderManager).initLoader(anyInt(), any(), any(LoaderManager.LoaderCallbacks::class.java))
Done

2021-07-08 11:57 UTC, cketti approved these changes
Thanks

2021-07-08 11:58 UTC, merged